name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest

    steps:
    - name: Show environments
      run: |
        sw_vers
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.2.app/Contents/Developer'
    - name: Checkout submodules
      run: |
        git submodule update --init
    - name: Lint Swift
      run: |
        brew install swiftlint
        swiftlint
    - name: Unit Test
      run: |
        set -o pipefail
        xcodebuild test -workspace CotEditor.xcworkspace -scheme CotEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
    - name: Unit Test for SyntaxMapBuilder
      run: |
        cd SyntaxMapBuilder
        swift build
        swift test 2>&1 | xcpretty -c
